<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="HPE Unified Functional Testing" productVer="14.02" os="" host="P3A-HYCQXJ2"><DocLocation><![CDATA[C:\Users\pdc3a-training.pdc3a\Documents\Unified Functional Testing\CaseStudy1]]></DocLocation></General>
<Doc rID="T1"   productName= "HPE Unified Functional Testing"  >
<DName><![CDATA[CaseStudy1]]></DName>
<Res><![CDATA[Res129]]></Res>
<RunType fmStep="True" /><DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<Action rID="T3">
<AName><![CDATA[Action1]]></AName>
<Step rID="T4">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[9/19/2019 - 12:52:19]]></Time>
<TimeTick>1568877739</TimeTick>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[fromCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Los Angeles"]]></Details>
<Time><![CDATA[9/19/2019 - 12:52:19]]></Time>
<TimeTick>1568877739</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="9" Source="Action1" SourceLine="150" >
<Disp><![CDATA[fromCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[toCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["London"]]></Details>
<Time><![CDATA[9/19/2019 - 12:52:20]]></Time>
<TimeTick>1568877740</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="11" Source="Action1" SourceLine="151" >
<Disp><![CDATA[toCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[numOfTickets.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["3"]]></Details>
<Time><![CDATA[9/19/2019 - 12:52:28]]></Time>
<TimeTick>1568877748</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="13" Source="Action1" SourceLine="152" >
<Disp><![CDATA[numOfTickets.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[numOfTickets.GetROProperty]]></Obj>
<Details plainTxt="False" ><![CDATA["value"]]></Details>
<Time><![CDATA[9/19/2019 - 12:52:28]]></Time>
<TimeTick>1568877748</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="15" Source="Action1" SourceLine="153" >
<Disp><![CDATA[numOfTickets.GetROProperty]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[FIND FLIGHTS.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/19/2019 - 12:52:39]]></Time>
<TimeTick>1568877759</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="17" Source="Action1" SourceLine="155" >
<Disp><![CDATA[FIND FLIGHTS.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[flightsDataGrid.SelectCell]]></Obj>
<Details plainTxt="False" ><![CDATA[0, 1]]></Details>
<Time><![CDATA[9/19/2019 - 12:52:39]]></Time>
<TimeTick>1568877759</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="19" Source="Action1" SourceLine="156" >
<Disp><![CDATA[flightsDataGrid.SelectCell]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[SELECT FLIGHT.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/19/2019 - 12:52:47]]></Time>
<TimeTick>1568877767</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="21" Source="Action1" SourceLine="157" >
<Disp><![CDATA[SELECT FLIGHT.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[$108.60.GetROProperty]]></Obj>
<Details plainTxt="False" ><![CDATA["name"]]></Details>
<Time><![CDATA[9/19/2019 - 12:52:49]]></Time>
<TimeTick>1568877769</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="23" Source="Action1" SourceLine="159" >
<Disp><![CDATA[$108.60.GetROProperty]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[$325.80.GetROProperty]]></Obj>
<Details plainTxt="False" ><![CDATA["name"]]></Details>
<Time><![CDATA[9/19/2019 - 12:52:50]]></Time>
<TimeTick>1568877770</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="25" Source="Action1" SourceLine="160" >
<Disp><![CDATA[$325.80.GetROProperty]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="8" Source="Action1" SourceLine="150" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj ><![CDATA[Total_Price]]></Obj>
<Details ><![CDATA[Price calculated correctly]]></Details>
<Time><![CDATA[9/19/2019 - 12:52:53]]></Time>
<TimeTick>1568877773</TimeTick>
<NodeArgs eType="User" icon="9" nRep="26" status="Passed" Source="Action1" SourceLine="166" >
<Disp><![CDATA[Total_Price]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="9/19/2019 - 12:52:12" eTime="9/19/2019 - 12:52:53" passed="1" failed="0" warnings="0" ><Param paramInOut = "In"><ParamName><![CDATA[Param1]]></ParamName><ParamVal><![CDATA[3]]></ParamVal>
</Param>
</Summary>
<NodeArgs eType="StartAction" icon="3" nRep="6" status="Passed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<Summary sTime="9/19/2019 - 12:52:10" eTime="9/19/2019 - 12:52:53" passed="1" failed="0" warnings="0" ><Param paramInOut = "In"><ParamName><![CDATA[Param1]]></ParamName><ParamVal><![CDATA[3]]></ParamVal>
</Param>
</Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Passed" >
<Disp><![CDATA[Test CaseStudy1 Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>