<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="HPE Unified Functional Testing" productVer="14.02" os="" host="P3A-HYCQXJ2"><DocLocation><![CDATA[C:\Users\pdc3a-training.pdc3a\Documents\Unified Functional Testing\CaseStudy1]]></DocLocation></General>
<Doc rID="T1"   productName= "HPE Unified Functional Testing"  >
<DName><![CDATA[CaseStudy1]]></DName>
<Res><![CDATA[Res163]]></Res>
<RunType fmStep="True" /><DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<Action rID="T3">
<AName><![CDATA[Action1]]></AName>
<Step rID="T4">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[9/19/2019 - 16:19:40]]></Time>
<TimeTick>1568890180</TimeTick>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[fromCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["London"]]></Details>
<Time><![CDATA[9/19/2019 - 16:19:40]]></Time>
<TimeTick>1568890180</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="9" Source="Action1" SourceLine="203" >
<Disp><![CDATA[fromCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[toCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Paris"]]></Details>
<Time><![CDATA[9/19/2019 - 16:19:41]]></Time>
<TimeTick>1568890181</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="11" Source="Action1" SourceLine="204" >
<Disp><![CDATA[toCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[datePicker.SetDate]]></Obj>
<Details plainTxt="False" ><![CDATA["1-Oct-2019"]]></Details>
<Time><![CDATA[9/19/2019 - 16:19:41]]></Time>
<TimeTick>1568890181</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="13" Source="Action1" SourceLine="206" >
<Disp><![CDATA[datePicker.SetDate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[FIND FLIGHTS.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/19/2019 - 16:19:46]]></Time>
<TimeTick>1568890186</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="15" Source="Action1" SourceLine="208" >
<Disp><![CDATA[FIND FLIGHTS.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[flightsDataGrid.RowCount]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/19/2019 - 16:19:47]]></Time>
<TimeTick>1568890187</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="17" Source="Action1" SourceLine="210" >
<Disp><![CDATA[flightsDataGrid.RowCount]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[BACK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/19/2019 - 16:19:47]]></Time>
<TimeTick>1568890187</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="19" Source="Action1" SourceLine="212" >
<Disp><![CDATA[BACK.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[fromCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["London"]]></Details>
<Time><![CDATA[9/19/2019 - 16:19:47]]></Time>
<TimeTick>1568890187</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="21" Source="Action1" SourceLine="203" >
<Disp><![CDATA[fromCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[toCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Paris"]]></Details>
<Time><![CDATA[9/19/2019 - 16:19:54]]></Time>
<TimeTick>1568890194</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="23" Source="Action1" SourceLine="204" >
<Disp><![CDATA[toCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[datePicker.SetDate]]></Obj>
<Details plainTxt="False" ><![CDATA["2-Oct-2019"]]></Details>
<Time><![CDATA[9/19/2019 - 16:19:54]]></Time>
<TimeTick>1568890194</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="25" Source="Action1" SourceLine="206" >
<Disp><![CDATA[datePicker.SetDate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[FIND FLIGHTS.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/19/2019 - 16:19:54]]></Time>
<TimeTick>1568890194</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="27" Source="Action1" SourceLine="208" >
<Disp><![CDATA[FIND FLIGHTS.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[flightsDataGrid.RowCount]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/19/2019 - 16:19:55]]></Time>
<TimeTick>1568890195</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="29" Source="Action1" SourceLine="210" >
<Disp><![CDATA[flightsDataGrid.RowCount]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[BACK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/19/2019 - 16:19:58]]></Time>
<TimeTick>1568890198</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="31" Source="Action1" SourceLine="212" >
<Disp><![CDATA[BACK.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[fromCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["London"]]></Details>
<Time><![CDATA[9/19/2019 - 16:19:59]]></Time>
<TimeTick>1568890199</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="33" Source="Action1" SourceLine="203" >
<Disp><![CDATA[fromCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[toCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Paris"]]></Details>
<Time><![CDATA[9/19/2019 - 16:19:59]]></Time>
<TimeTick>1568890199</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="35" Source="Action1" SourceLine="204" >
<Disp><![CDATA[toCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[datePicker.SetDate]]></Obj>
<Details plainTxt="False" ><![CDATA["3-Oct-2019"]]></Details>
<Time><![CDATA[9/19/2019 - 16:19:59]]></Time>
<TimeTick>1568890199</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="37" Source="Action1" SourceLine="206" >
<Disp><![CDATA[datePicker.SetDate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[FIND FLIGHTS.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/19/2019 - 16:19:59]]></Time>
<TimeTick>1568890199</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="39" Source="Action1" SourceLine="208" >
<Disp><![CDATA[FIND FLIGHTS.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[flightsDataGrid.RowCount]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/19/2019 - 16:20:05]]></Time>
<TimeTick>1568890205</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="41" Source="Action1" SourceLine="210" >
<Disp><![CDATA[flightsDataGrid.RowCount]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[BACK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/19/2019 - 16:20:06]]></Time>
<TimeTick>1568890206</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="43" Source="Action1" SourceLine="212" >
<Disp><![CDATA[BACK.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[fromCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["London"]]></Details>
<Time><![CDATA[9/19/2019 - 16:20:06]]></Time>
<TimeTick>1568890206</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="45" Source="Action1" SourceLine="203" >
<Disp><![CDATA[fromCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[toCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Paris"]]></Details>
<Time><![CDATA[9/19/2019 - 16:20:07]]></Time>
<TimeTick>1568890207</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="47" Source="Action1" SourceLine="204" >
<Disp><![CDATA[toCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[datePicker.SetDate]]></Obj>
<Details plainTxt="False" ><![CDATA["4-Oct-2019"]]></Details>
<Time><![CDATA[9/19/2019 - 16:20:13]]></Time>
<TimeTick>1568890213</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="49" Source="Action1" SourceLine="206" >
<Disp><![CDATA[datePicker.SetDate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[FIND FLIGHTS.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/19/2019 - 16:20:13]]></Time>
<TimeTick>1568890213</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="51" Source="Action1" SourceLine="208" >
<Disp><![CDATA[FIND FLIGHTS.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[flightsDataGrid.RowCount]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/19/2019 - 16:20:13]]></Time>
<TimeTick>1568890213</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="53" Source="Action1" SourceLine="210" >
<Disp><![CDATA[flightsDataGrid.RowCount]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[BACK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/19/2019 - 16:20:13]]></Time>
<TimeTick>1568890213</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="55" Source="Action1" SourceLine="212" >
<Disp><![CDATA[BACK.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[fromCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["London"]]></Details>
<Time><![CDATA[9/19/2019 - 16:20:14]]></Time>
<TimeTick>1568890214</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="57" Source="Action1" SourceLine="203" >
<Disp><![CDATA[fromCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[toCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Paris"]]></Details>
<Time><![CDATA[9/19/2019 - 16:20:20]]></Time>
<TimeTick>1568890220</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="59" Source="Action1" SourceLine="204" >
<Disp><![CDATA[toCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[datePicker.SetDate]]></Obj>
<Details plainTxt="False" ><![CDATA["5-Oct-2019"]]></Details>
<Time><![CDATA[9/19/2019 - 16:20:21]]></Time>
<TimeTick>1568890221</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="61" Source="Action1" SourceLine="206" >
<Disp><![CDATA[datePicker.SetDate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[FIND FLIGHTS.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/19/2019 - 16:20:21]]></Time>
<TimeTick>1568890221</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="63" Source="Action1" SourceLine="208" >
<Disp><![CDATA[FIND FLIGHTS.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[flightsDataGrid.RowCount]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/19/2019 - 16:20:21]]></Time>
<TimeTick>1568890221</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="65" Source="Action1" SourceLine="210" >
<Disp><![CDATA[flightsDataGrid.RowCount]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[BACK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/19/2019 - 16:20:21]]></Time>
<TimeTick>1568890221</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="67" Source="Action1" SourceLine="212" >
<Disp><![CDATA[BACK.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[fromCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["London"]]></Details>
<Time><![CDATA[9/19/2019 - 16:20:28]]></Time>
<TimeTick>1568890228</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="69" Source="Action1" SourceLine="203" >
<Disp><![CDATA[fromCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[toCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Paris"]]></Details>
<Time><![CDATA[9/19/2019 - 16:20:28]]></Time>
<TimeTick>1568890228</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="71" Source="Action1" SourceLine="204" >
<Disp><![CDATA[toCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[datePicker.SetDate]]></Obj>
<Details plainTxt="False" ><![CDATA["6-Oct-2019"]]></Details>
<Time><![CDATA[9/19/2019 - 16:20:29]]></Time>
<TimeTick>1568890229</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="73" Source="Action1" SourceLine="206" >
<Disp><![CDATA[datePicker.SetDate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[FIND FLIGHTS.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/19/2019 - 16:20:29]]></Time>
<TimeTick>1568890229</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="75" Source="Action1" SourceLine="208" >
<Disp><![CDATA[FIND FLIGHTS.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[flightsDataGrid.RowCount]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/19/2019 - 16:20:35]]></Time>
<TimeTick>1568890235</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="77" Source="Action1" SourceLine="210" >
<Disp><![CDATA[flightsDataGrid.RowCount]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[BACK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/19/2019 - 16:20:36]]></Time>
<TimeTick>1568890236</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="79" Source="Action1" SourceLine="212" >
<Disp><![CDATA[BACK.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[fromCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["London"]]></Details>
<Time><![CDATA[9/19/2019 - 16:20:36]]></Time>
<TimeTick>1568890236</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="81" Source="Action1" SourceLine="203" >
<Disp><![CDATA[fromCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[toCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Paris"]]></Details>
<Time><![CDATA[9/19/2019 - 16:20:36]]></Time>
<TimeTick>1568890236</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="83" Source="Action1" SourceLine="204" >
<Disp><![CDATA[toCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[datePicker.SetDate]]></Obj>
<Details plainTxt="False" ><![CDATA["7-Oct-2019"]]></Details>
<Time><![CDATA[9/19/2019 - 16:20:43]]></Time>
<TimeTick>1568890243</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="85" Source="Action1" SourceLine="206" >
<Disp><![CDATA[datePicker.SetDate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[FIND FLIGHTS.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/19/2019 - 16:20:43]]></Time>
<TimeTick>1568890243</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="87" Source="Action1" SourceLine="208" >
<Disp><![CDATA[FIND FLIGHTS.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[flightsDataGrid.RowCount]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/19/2019 - 16:20:43]]></Time>
<TimeTick>1568890243</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="89" Source="Action1" SourceLine="210" >
<Disp><![CDATA[flightsDataGrid.RowCount]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[BACK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/19/2019 - 16:20:45]]></Time>
<TimeTick>1568890245</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="91" Source="Action1" SourceLine="212" >
<Disp><![CDATA[BACK.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[fromCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["London"]]></Details>
<Time><![CDATA[9/19/2019 - 16:20:46]]></Time>
<TimeTick>1568890246</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="93" Source="Action1" SourceLine="203" >
<Disp><![CDATA[fromCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[toCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Paris"]]></Details>
<Time><![CDATA[9/19/2019 - 16:20:46]]></Time>
<TimeTick>1568890246</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="95" Source="Action1" SourceLine="204" >
<Disp><![CDATA[toCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[datePicker.SetDate]]></Obj>
<Details plainTxt="False" ><![CDATA["8-Oct-2019"]]></Details>
<Time><![CDATA[9/19/2019 - 16:20:53]]></Time>
<TimeTick>1568890253</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="97" Source="Action1" SourceLine="206" >
<Disp><![CDATA[datePicker.SetDate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[FIND FLIGHTS.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/19/2019 - 16:20:53]]></Time>
<TimeTick>1568890253</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="99" Source="Action1" SourceLine="208" >
<Disp><![CDATA[FIND FLIGHTS.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[flightsDataGrid.RowCount]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/19/2019 - 16:20:53]]></Time>
<TimeTick>1568890253</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="101" Source="Action1" SourceLine="210" >
<Disp><![CDATA[flightsDataGrid.RowCount]]></Disp>
</NodeArgs>
</Step>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[BACK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/19/2019 - 16:20:53]]></Time>
<TimeTick>1568890253</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="103" Source="Action1" SourceLine="212" >
<Disp><![CDATA[BACK.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[fromCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["London"]]></Details>
<Time><![CDATA[9/19/2019 - 16:20:54]]></Time>
<TimeTick>1568890254</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="105" Source="Action1" SourceLine="203" >
<Disp><![CDATA[fromCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA[toCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Paris"]]></Details>
<Time><![CDATA[9/19/2019 - 16:21:00]]></Time>
<TimeTick>1568890260</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="107" Source="Action1" SourceLine="204" >
<Disp><![CDATA[toCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[datePicker.SetDate]]></Obj>
<Details plainTxt="False" ><![CDATA["9-Oct-2019"]]></Details>
<Time><![CDATA[9/19/2019 - 16:21:01]]></Time>
<TimeTick>1568890261</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="109" Source="Action1" SourceLine="206" >
<Disp><![CDATA[datePicker.SetDate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA[FIND FLIGHTS.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/19/2019 - 16:21:01]]></Time>
<TimeTick>1568890261</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="111" Source="Action1" SourceLine="208" >
<Disp><![CDATA[FIND FLIGHTS.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA[flightsDataGrid.RowCount]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/19/2019 - 16:21:01]]></Time>
<TimeTick>1568890261</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="113" Source="Action1" SourceLine="210" >
<Disp><![CDATA[flightsDataGrid.RowCount]]></Disp>
</NodeArgs>
</Step>
<Step rID="T58">
<Obj plainTxt="False" ><![CDATA[BACK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/19/2019 - 16:21:02]]></Time>
<TimeTick>1568890262</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="115" Source="Action1" SourceLine="212" >
<Disp><![CDATA[BACK.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T59">
<Obj plainTxt="False" ><![CDATA[fromCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["London"]]></Details>
<Time><![CDATA[9/19/2019 - 16:21:02]]></Time>
<TimeTick>1568890262</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="117" Source="Action1" SourceLine="203" >
<Disp><![CDATA[fromCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T60">
<Obj plainTxt="False" ><![CDATA[toCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Paris"]]></Details>
<Time><![CDATA[9/19/2019 - 16:21:03]]></Time>
<TimeTick>1568890263</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="119" Source="Action1" SourceLine="204" >
<Disp><![CDATA[toCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T61">
<Obj plainTxt="False" ><![CDATA[datePicker.SetDate]]></Obj>
<Details plainTxt="False" ><![CDATA["10-Oct-2019"]]></Details>
<Time><![CDATA[9/19/2019 - 16:21:03]]></Time>
<TimeTick>1568890263</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="121" Source="Action1" SourceLine="206" >
<Disp><![CDATA[datePicker.SetDate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T62">
<Obj plainTxt="False" ><![CDATA[FIND FLIGHTS.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/19/2019 - 16:21:03]]></Time>
<TimeTick>1568890263</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="123" Source="Action1" SourceLine="208" >
<Disp><![CDATA[FIND FLIGHTS.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T63">
<Obj plainTxt="False" ><![CDATA[flightsDataGrid.RowCount]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/19/2019 - 16:21:06]]></Time>
<TimeTick>1568890266</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="125" Source="Action1" SourceLine="210" >
<Disp><![CDATA[flightsDataGrid.RowCount]]></Disp>
</NodeArgs>
</Step>
<Step rID="T64">
<Obj plainTxt="False" ><![CDATA[BACK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/19/2019 - 16:21:07]]></Time>
<TimeTick>1568890267</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="127" Source="Action1" SourceLine="212" >
<Disp><![CDATA[BACK.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T65">
<Obj plainTxt="False" ><![CDATA[fromCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["London"]]></Details>
<Time><![CDATA[9/19/2019 - 16:21:07]]></Time>
<TimeTick>1568890267</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="129" Source="Action1" SourceLine="203" >
<Disp><![CDATA[fromCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T66">
<Obj plainTxt="False" ><![CDATA[toCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Paris"]]></Details>
<Time><![CDATA[9/19/2019 - 16:21:07]]></Time>
<TimeTick>1568890267</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="131" Source="Action1" SourceLine="204" >
<Disp><![CDATA[toCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T67">
<Obj plainTxt="False" ><![CDATA[datePicker.SetDate]]></Obj>
<Details plainTxt="False" ><![CDATA["11-Oct-2019"]]></Details>
<Time><![CDATA[9/19/2019 - 16:21:07]]></Time>
<TimeTick>1568890267</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="133" Source="Action1" SourceLine="206" >
<Disp><![CDATA[datePicker.SetDate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T68">
<Obj plainTxt="False" ><![CDATA[FIND FLIGHTS.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/19/2019 - 16:21:14]]></Time>
<TimeTick>1568890274</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="135" Source="Action1" SourceLine="208" >
<Disp><![CDATA[FIND FLIGHTS.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T69">
<Obj plainTxt="False" ><![CDATA[flightsDataGrid.RowCount]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/19/2019 - 16:21:14]]></Time>
<TimeTick>1568890274</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="137" Source="Action1" SourceLine="210" >
<Disp><![CDATA[flightsDataGrid.RowCount]]></Disp>
</NodeArgs>
</Step>
<Step rID="T70">
<Obj plainTxt="False" ><![CDATA[BACK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/19/2019 - 16:21:14]]></Time>
<TimeTick>1568890274</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="139" Source="Action1" SourceLine="212" >
<Disp><![CDATA[BACK.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T71">
<Obj plainTxt="False" ><![CDATA[fromCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["London"]]></Details>
<Time><![CDATA[9/19/2019 - 16:21:15]]></Time>
<TimeTick>1568890275</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="141" Source="Action1" SourceLine="203" >
<Disp><![CDATA[fromCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T72">
<Obj plainTxt="False" ><![CDATA[toCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Paris"]]></Details>
<Time><![CDATA[9/19/2019 - 16:21:17]]></Time>
<TimeTick>1568890277</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="143" Source="Action1" SourceLine="204" >
<Disp><![CDATA[toCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T73">
<Obj plainTxt="False" ><![CDATA[datePicker.SetDate]]></Obj>
<Details plainTxt="False" ><![CDATA["12-Oct-2019"]]></Details>
<Time><![CDATA[9/19/2019 - 16:21:17]]></Time>
<TimeTick>1568890277</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="145" Source="Action1" SourceLine="206" >
<Disp><![CDATA[datePicker.SetDate]]></Disp>
</NodeArgs>
</Step>