<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="HPE Unified Functional Testing" productVer="14.02" os="" host="P3A-HYCQXJ2"><DocLocation><![CDATA[C:\Users\pdc3a-training.pdc3a\Documents\Unified Functional Testing\E2E]]></DocLocation></General>
<Doc rID="T1"   productName= "HPE Unified Functional Testing"  >
<DName><![CDATA[E2E]]></DName>
<Res><![CDATA[Res2]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Step rID="T4">
<Obj plainTxt="False" ><![CDATA[StartUp Browser]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[9/13/2019 - 14:34:35]]></Time>
<TimeTick>1568365475</TimeTick>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[StartUp Browser.Navigate]]></Obj>
<Details plainTxt="False" ><![CDATA[Navigate to http://newtours.demoaut.com]]></Details>
<Time><![CDATA[9/13/2019 - 14:34:35]]></Time>
<TimeTick>1568365475</TimeTick>
<NodeArgs eType="Replay" icon="4" nRep="9" Source="Action0" SourceLine="-1" >
<Disp><![CDATA[StartUp Browser.Navigate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[StartUp Browser.Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/13/2019 - 14:34:37]]></Time>
<TimeTick>1568365477</TimeTick>
<NodeArgs eType="Replay" icon="4" nRep="11" Source="Action0" SourceLine="-1" >
<Disp><![CDATA[StartUp Browser.Sync]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="8" Source="Action0" SourceLine="-1" >
<Disp><![CDATA[StartUp Browser]]></Disp>
</NodeArgs>
</Step>
<Action rID="T7">
<AName><![CDATA[Action1]]></AName>
<Action rID="T8">
<AName><![CDATA[Action1 [Registration]]]></AName>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Welcome: Mercury Tours]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[9/13/2019 - 14:34:37]]></Time>
<TimeTick>1568365477</TimeTick>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[Welcome: Mercury Tours]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[9/13/2019 - 14:34:37]]></Time>
<TimeTick>1568365477</TimeTick>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[REGISTER.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/13/2019 - 14:34:37]]></Time>
<TimeTick>1568365477</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="18" Source="Action1 [Registration]" SourceLine="0" >
<Disp><![CDATA[REGISTER.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="17" Source="Action1 [Registration]" SourceLine="0" >
<Disp><![CDATA[Welcome: Mercury Tours]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Register: Mercury Tours]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[9/13/2019 - 14:34:38]]></Time>
<TimeTick>1568365478</TimeTick>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[firstName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["s"]]></Details>
<Time><![CDATA[9/13/2019 - 14:34:38]]></Time>
<TimeTick>1568365478</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="22" Source="Action1 [Registration]" SourceLine="1" >
<Disp><![CDATA[firstName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[firstName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["suraj"]]></Details>
<Time><![CDATA[9/13/2019 - 14:34:39]]></Time>
<TimeTick>1568365479</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="25" Source="Action1 [Registration]" SourceLine="2" >
<Disp><![CDATA[firstName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[lastName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["w"]]></Details>
<Time><![CDATA[9/13/2019 - 14:34:39]]></Time>
<TimeTick>1568365479</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="28" Source="Action1 [Registration]" SourceLine="3" >
<Disp><![CDATA[lastName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[phone.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["7894561230"]]></Details>
<Time><![CDATA[9/13/2019 - 14:34:39]]></Time>
<TimeTick>1568365479</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="31" Source="Action1 [Registration]" SourceLine="4" >
<Disp><![CDATA[phone.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[userName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["s@gmail.com"]]></Details>
<Time><![CDATA[9/13/2019 - 14:34:39]]></Time>
<TimeTick>1568365479</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="34" Source="Action1 [Registration]" SourceLine="5" >
<Disp><![CDATA[userName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[address1.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["pune"]]></Details>
<Time><![CDATA[9/13/2019 - 14:34:39]]></Time>
<TimeTick>1568365479</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="37" Source="Action1 [Registration]" SourceLine="6" >
<Disp><![CDATA[address1.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[address2.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["pune"]]></Details>
<Time><![CDATA[9/13/2019 - 14:34:39]]></Time>
<TimeTick>1568365479</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="40" Source="Action1 [Registration]" SourceLine="7" >
<Disp><![CDATA[address2.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[city.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["pune"]]></Details>
<Time><![CDATA[9/13/2019 - 14:34:40]]></Time>
<TimeTick>1568365480</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="43" Source="Action1 [Registration]" SourceLine="8" >
<Disp><![CDATA[city.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[state.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["mh"]]></Details>
<Time><![CDATA[9/13/2019 - 14:34:40]]></Time>
<TimeTick>1568365480</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="46" Source="Action1 [Registration]" SourceLine="9" >
<Disp><![CDATA[state.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[postalCode.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["411046"]]></Details>
<Time><![CDATA[9/13/2019 - 14:34:40]]></Time>
<TimeTick>1568365480</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="49" Source="Action1 [Registration]" SourceLine="10" >
<Disp><![CDATA[postalCode.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[country.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["ICELAND"]]></Details>
<Time><![CDATA[9/13/2019 - 14:34:40]]></Time>
<TimeTick>1568365480</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="52" Source="Action1 [Registration]" SourceLine="11" >
<Disp><![CDATA[country.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[country.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["INDIA"]]></Details>
<Time><![CDATA[9/13/2019 - 14:34:40]]></Time>
<TimeTick>1568365480</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="55" Source="Action1 [Registration]" SourceLine="12" >
<Disp><![CDATA[country.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[email.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["user1"]]></Details>
<Time><![CDATA[9/13/2019 - 14:34:40]]></Time>
<TimeTick>1568365480</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="58" Source="Action1 [Registration]" SourceLine="13" >
<Disp><![CDATA[email.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[password.SetSecure]]></Obj>
<Details plainTxt="False" ><![CDATA["5d7b59fdf137c9269234b3471290bfb0"]]></Details>
<Time><![CDATA[9/13/2019 - 14:34:41]]></Time>
<TimeTick>1568365481</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="61" Source="Action1 [Registration]" SourceLine="14" >
<Disp><![CDATA[password.SetSecure]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[confirmPassword.SetSecure]]></Obj>
<Details plainTxt="False" ><![CDATA["5d7b5a01dcbe4f2cc6ac101eaebea3c2"]]></Details>
<Time><![CDATA[9/13/2019 - 14:34:41]]></Time>
<TimeTick>1568365481</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="64" Source="Action1 [Registration]" SourceLine="15" >
<Disp><![CDATA[confirmPassword.SetSecure]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[register.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/13/2019 - 14:34:41]]></Time>
<TimeTick>1568365481</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="67" Source="Action1 [Registration]" SourceLine="16" >
<Disp><![CDATA[register.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="21" Source="Action1 [Registration]" SourceLine="1" >
<Disp><![CDATA[Register: Mercury Tours]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="16" Source="Action1 [Registration]" SourceLine="0" >
<Disp><![CDATA[Welcome: Mercury Tours]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="9/13/2019 - 14:34:37" eTime="9/13/2019 - 14:34:41" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="6" nRep="13" >
<Disp><![CDATA[Action1 [Registration] Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T29">
<AName><![CDATA[Action1 [LoginTest]]]></AName>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[Welcome: Mercury Tours]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[9/13/2019 - 14:35:01]]></Time>
<TimeTick>1568365501</TimeTick>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[Welcome: Mercury Tours]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[9/13/2019 - 14:35:01]]></Time>
<TimeTick>1568365501</TimeTick>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[userName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["user1"]]></Details>
<Time><![CDATA[9/13/2019 - 14:35:01]]></Time>
<TimeTick>1568365501</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="74" Source="Action1 [LoginTest]" SourceLine="1" >
<Disp><![CDATA[userName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[password]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;identify&nbsp;the&nbsp;object&nbsp;"password"&nbsp;(of&nbsp;class&nbsp;WebEdit).<br/>Verify&nbsp;that&nbsp;this&nbsp;object's&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[9/13/2019 - 14:35:28]]></Time>
<TimeTick>1568365528</TimeTick>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[password]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Type = password<br>Mercury Class = WebEdit<br>Html Tag = INPUT<br>_xpath = //DIV[1]/TABLE[1]/TBODY[1]/TR[1]/TD[2]/TABLE[1]/TBODY[1]/TR[4]/TD[1]/TABLE[1]/TBODY[1]/TR[1]/TD[2]/TABLE[1]/TBODY[1]/TR[2]/TD[3]/FORM[1]/TABLE[1]/TBODY[1]/TR[4]/TD[1]/TABLE[1]/TBODY[1]/TR[3]/TD[2]/INPUT[1]<br>|rows = 0<br>placeholder = <br>Name = password<br>Max Length = 524288<br>Html Id = <br>default value = <br>DHTML Class = <br>acc_name = <br>]]></Details>
<Time><![CDATA[9/13/2019 - 14:35:28]]></Time>
<TimeTick>1568365528</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="119" status="Warning" nType="Description" Source="Action1 [LoginTest]" SourceLine="2" >
<Disp><![CDATA[password]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="9" nRep="118" status="Failed" nType="Run Error" Source="Action1 [LoginTest]" SourceLine="2" >
<Disp><![CDATA[password]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="73" status="Failed" Source="Action1 [LoginTest]" SourceLine="1" >
<Disp><![CDATA[Welcome: Mercury Tours]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="72" status="Failed" Source="Action1 [LoginTest]" SourceLine="1" >
<Disp><![CDATA[Welcome: Mercury Tours]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[Welcome: Mercury Tours]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[9/13/2019 - 14:35:28]]></Time>
<TimeTick>1568365528</TimeTick>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object &quot;password&quot; (of class WebEdit).<BR/>Verify that this object's properties match an object currently displayed in your application.<BR/>Line (3): &quot;Browser(&quot;Welcome: Mercury Tours&quot;).Page(&quot;Welcome: Mercury Tours&quot;).WebEdit(&quot;password&quot;).SetSecure &quot;5d7b5aa797916d966b50c21a3e06&quot;&quot;. ]]></Details>
<Time><![CDATA[9/13/2019 - 14:35:28]]></Time>
<TimeTick>1568365528</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="121" status="Failed" Source="Action1 [LoginTest]" SourceLine="2" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[Welcome: Mercury Tours]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[9/13/2019 - 14:35:53]]></Time>
<TimeTick>1568365553</TimeTick>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[Sign-In]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;identify&nbsp;the&nbsp;object&nbsp;"Sign-In"&nbsp;(of&nbsp;class&nbsp;Image).<br/>Verify&nbsp;that&nbsp;this&nbsp;object's&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[9/13/2019 - 14:35:53]]></Time>
<TimeTick>1568365553</TimeTick>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[Sign-In]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Mercury Class = Image<br>Html Tag = INPUT<br>_xpath = //DIV[1]/TABLE[1]/TBODY[1]/TR[1]/TD[2]/TABLE[1]/TBODY[1]/TR[4]/TD[1]/TABLE[1]/TBODY[1]/TR[1]/TD[2]/TABLE[1]/TBODY[1]/TR[2]/TD[3]/FORM[1]/TABLE[1]/TBODY[1]/TR[4]/TD[1]/TABLE[1]/TBODY[1]/TR[4]/TD[2]/DIV[1]/INPUT[1]<br>|Width = 58<br>Visible = -1<br>Name = login<br>Image Type = Image Button<br>Html Id = <br>Height = 17<br>file name = btn_signin.gif?osCsid=76f53f5a0e537c337640c3b607dcd252<br>DHTML Class = <br>Alt = Sign-In<br>]]></Details>
<Time><![CDATA[9/13/2019 - 14:35:53]]></Time>
<TimeTick>1568365553</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="165" status="Warning" nType="Description" Source="Action1 [LoginTest]" SourceLine="2" >
<Disp><![CDATA[Sign-In]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="11" nRep="164" status="Failed" nType="Run Error" Source="Action1 [LoginTest]" SourceLine="2" >
<Disp><![CDATA[Sign-In]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="163" status="Failed" Source="Action1 [LoginTest]" SourceLine="2" >
<Disp><![CDATA[Welcome: Mercury Tours]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="120" status="Failed" Source="Action1 [LoginTest]" SourceLine="2" >
<Disp><![CDATA[Welcome: Mercury Tours]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[Welcome: Mercury Tours]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[9/13/2019 - 14:35:53]]></Time>
<TimeTick>1568365553</TimeTick>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object &quot;Sign-In&quot; (of class Image).<BR/>Verify that this object's properties match an object currently displayed in your application.<BR/>Line (4): &quot;Browser(&quot;Welcome: Mercury Tours&quot;).Page(&quot;Welcome: Mercury Tours&quot;).Image(&quot;Sign-In&quot;).Click 47,11&quot;. ]]></Details>
<Time><![CDATA[9/13/2019 - 14:35:53]]></Time>
<TimeTick>1568365553</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="167" status="Failed" Source="Action1 [LoginTest]" SourceLine="3" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="166" status="Failed" Source="Action1 [LoginTest]" SourceLine="3" >
<Disp><![CDATA[Welcome: Mercury Tours]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="9/13/2019 - 14:34:41" eTime="9/13/2019 - 14:35:56" passed="0" failed="4" warnings="2" ></Summary>
<NodeArgs eType="StartAction" icon="6" nRep="69" status="Failed" >
<Disp><![CDATA[Action1 [LoginTest] Summary]]></Disp>
</NodeArgs>
</Action>
<Summary sTime="9/13/2019 - 14:34:37" eTime="9/13/2019 - 14:35:56" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="5" nRep="12" status="Failed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" status="Failed" >
<Disp><![CDATA[E2E Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="9/13/2019 - 14:34:35" eTime="9/13/2019 - 14:35:56" passed="0" failed="4" warnings="2" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Failed" >
<Disp><![CDATA[Test E2E Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>