<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="HPE Unified Functional Testing" productVer="14.02" os="" host="P3A-HYCQXJ2"><DocLocation><![CDATA[C:\Users\pdc3a-training.pdc3a\Documents\Unified Functional Testing\Debugging]]></DocLocation></General>
<Doc rID="T1"   productName= "HPE Unified Functional Testing"  >
<DName><![CDATA[Debugging]]></DName>
<Res><![CDATA[Res5]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action1]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[9/17/2019 - 12:36:10]]></Time>
<TimeTick>1568703970</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[agentName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["john"]]></Details>
<Time><![CDATA[9/17/2019 - 12:36:10]]></Time>
<TimeTick>1568703970</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="10" Source="Action1" SourceLine="1" >
<Disp><![CDATA[agentName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[password.SetSecure]]></Obj>
<Details plainTxt="False" ><![CDATA["5d808427ef16a34d2e81"]]></Details>
<Time><![CDATA[9/17/2019 - 12:36:11]]></Time>
<TimeTick>1568703971</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="12" Source="Action1" SourceLine="2" >
<Disp><![CDATA[password.SetSecure]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[OK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/17/2019 - 12:36:11]]></Time>
<TimeTick>1568703971</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="14" Source="Action1" SourceLine="3" >
<Disp><![CDATA[OK.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[fromCity.GetItemsCount]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/17/2019 - 12:36:12]]></Time>
<TimeTick>1568703972</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="16" Source="Action1" SourceLine="5" >
<Disp><![CDATA[fromCity.GetItemsCount]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[fromCity.GetItem]]></Obj>
<Details plainTxt="False" ><![CDATA[0]]></Details>
<Time><![CDATA[9/17/2019 - 12:36:12]]></Time>
<TimeTick>1568703972</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="18" Source="Action1" SourceLine="7" >
<Disp><![CDATA[fromCity.GetItem]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[fromCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Denver"]]></Details>
<Time><![CDATA[9/17/2019 - 12:36:13]]></Time>
<TimeTick>1568703973</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="20" Source="Action1" SourceLine="8" >
<Disp><![CDATA[fromCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[fromCity.GetItem]]></Obj>
<Details plainTxt="False" ><![CDATA[1]]></Details>
<Time><![CDATA[9/17/2019 - 12:36:13]]></Time>
<TimeTick>1568703973</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="22" Source="Action1" SourceLine="9" >
<Disp><![CDATA[fromCity.GetItem]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[toCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Frankfurt"]]></Details>
<Time><![CDATA[9/17/2019 - 12:36:14]]></Time>
<TimeTick>1568703974</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="24" Source="Action1" SourceLine="10" >
<Disp><![CDATA[toCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[FIND FLIGHTS.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/17/2019 - 12:36:14]]></Time>
<TimeTick>1568703974</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="26" Source="Action1" SourceLine="11" >
<Disp><![CDATA[FIND FLIGHTS.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[BACK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/17/2019 - 12:36:15]]></Time>
<TimeTick>1568703975</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="28" Source="Action1" SourceLine="12" >
<Disp><![CDATA[BACK.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[fromCity.GetItem]]></Obj>
<Details plainTxt="False" ><![CDATA[1]]></Details>
<Time><![CDATA[9/17/2019 - 12:36:15]]></Time>
<TimeTick>1568703975</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="30" Source="Action1" SourceLine="7" >
<Disp><![CDATA[fromCity.GetItem]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[fromCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Frankfurt"]]></Details>
<Time><![CDATA[9/17/2019 - 12:36:16]]></Time>
<TimeTick>1568703976</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="32" Source="Action1" SourceLine="8" >
<Disp><![CDATA[fromCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[fromCity.GetItem]]></Obj>
<Details plainTxt="False" ><![CDATA[2]]></Details>
<Time><![CDATA[9/17/2019 - 12:36:16]]></Time>
<TimeTick>1568703976</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="34" Source="Action1" SourceLine="9" >
<Disp><![CDATA[fromCity.GetItem]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[toCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["London"]]></Details>
<Time><![CDATA[9/17/2019 - 12:36:16]]></Time>
<TimeTick>1568703976</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="36" Source="Action1" SourceLine="10" >
<Disp><![CDATA[toCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[FIND FLIGHTS.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/17/2019 - 12:36:17]]></Time>
<TimeTick>1568703977</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="38" Source="Action1" SourceLine="11" >
<Disp><![CDATA[FIND FLIGHTS.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[BACK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/17/2019 - 12:36:17]]></Time>
<TimeTick>1568703977</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="40" Source="Action1" SourceLine="12" >
<Disp><![CDATA[BACK.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[fromCity.GetItem]]></Obj>
<Details plainTxt="False" ><![CDATA[2]]></Details>
<Time><![CDATA[9/17/2019 - 12:36:17]]></Time>
<TimeTick>1568703977</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="42" Source="Action1" SourceLine="7" >
<Disp><![CDATA[fromCity.GetItem]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[fromCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["London"]]></Details>
<Time><![CDATA[9/17/2019 - 12:36:18]]></Time>
<TimeTick>1568703978</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="44" Source="Action1" SourceLine="8" >
<Disp><![CDATA[fromCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[fromCity.GetItem]]></Obj>
<Details plainTxt="False" ><![CDATA[3]]></Details>
<Time><![CDATA[9/17/2019 - 12:36:18]]></Time>
<TimeTick>1568703978</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="46" Source="Action1" SourceLine="9" >
<Disp><![CDATA[fromCity.GetItem]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[toCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Los Angeles"]]></Details>
<Time><![CDATA[9/17/2019 - 12:36:19]]></Time>
<TimeTick>1568703979</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="48" Source="Action1" SourceLine="10" >
<Disp><![CDATA[toCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[FIND FLIGHTS.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/17/2019 - 12:36:19]]></Time>
<TimeTick>1568703979</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="50" Source="Action1" SourceLine="11" >
<Disp><![CDATA[FIND FLIGHTS.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[BACK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/17/2019 - 12:36:19]]></Time>
<TimeTick>1568703979</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="52" Source="Action1" SourceLine="12" >
<Disp><![CDATA[BACK.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[fromCity.GetItem]]></Obj>
<Details plainTxt="False" ><![CDATA[3]]></Details>
<Time><![CDATA[9/17/2019 - 12:36:20]]></Time>
<TimeTick>1568703980</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="54" Source="Action1" SourceLine="7" >
<Disp><![CDATA[fromCity.GetItem]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[fromCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Los Angeles"]]></Details>
<Time><![CDATA[9/17/2019 - 12:36:20]]></Time>
<TimeTick>1568703980</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="56" Source="Action1" SourceLine="8" >
<Disp><![CDATA[fromCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[fromCity.GetItem]]></Obj>
<Details plainTxt="False" ><![CDATA[4]]></Details>
<Time><![CDATA[9/17/2019 - 12:36:21]]></Time>
<TimeTick>1568703981</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="58" Source="Action1" SourceLine="9" >
<Disp><![CDATA[fromCity.GetItem]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[toCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Paris"]]></Details>
<Time><![CDATA[9/17/2019 - 12:36:21]]></Time>
<TimeTick>1568703981</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="60" Source="Action1" SourceLine="10" >
<Disp><![CDATA[toCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[FIND FLIGHTS.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/17/2019 - 12:36:21]]></Time>
<TimeTick>1568703981</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="62" Source="Action1" SourceLine="11" >
<Disp><![CDATA[FIND FLIGHTS.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[BACK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/17/2019 - 12:36:22]]></Time>
<TimeTick>1568703982</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="64" Source="Action1" SourceLine="12" >
<Disp><![CDATA[BACK.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[fromCity.GetItem]]></Obj>
<Details plainTxt="False" ><![CDATA[4]]></Details>
<Time><![CDATA[9/17/2019 - 12:36:22]]></Time>
<TimeTick>1568703982</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="66" Source="Action1" SourceLine="7" >
<Disp><![CDATA[fromCity.GetItem]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[fromCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Paris"]]></Details>
<Time><![CDATA[9/17/2019 - 12:36:23]]></Time>
<TimeTick>1568703983</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="68" Source="Action1" SourceLine="8" >
<Disp><![CDATA[fromCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[fromCity.GetItem]]></Obj>
<Details plainTxt="False" ><![CDATA[5]]></Details>
<Time><![CDATA[9/17/2019 - 12:36:23]]></Time>
<TimeTick>1568703983</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="70" Source="Action1" SourceLine="9" >
<Disp><![CDATA[fromCity.GetItem]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[toCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Portland"]]></Details>
<Time><![CDATA[9/17/2019 - 12:36:23]]></Time>
<TimeTick>1568703983</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="72" Source="Action1" SourceLine="10" >
<Disp><![CDATA[toCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[FIND FLIGHTS.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/17/2019 - 12:36:24]]></Time>
<TimeTick>1568703984</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="74" Source="Action1" SourceLine="11" >
<Disp><![CDATA[FIND FLIGHTS.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[BACK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/17/2019 - 12:36:24]]></Time>
<TimeTick>1568703984</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="76" Source="Action1" SourceLine="12" >
<Disp><![CDATA[BACK.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[fromCity.GetItem]]></Obj>
<Details plainTxt="False" ><![CDATA[5]]></Details>
<Time><![CDATA[9/17/2019 - 12:36:24]]></Time>
<TimeTick>1568703984</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="78" Source="Action1" SourceLine="7" >
<Disp><![CDATA[fromCity.GetItem]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[fromCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Portland"]]></Details>
<Time><![CDATA[9/17/2019 - 12:36:25]]></Time>
<TimeTick>1568703985</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="80" Source="Action1" SourceLine="8" >
<Disp><![CDATA[fromCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[fromCity.GetItem]]></Obj>
<Details plainTxt="False" ><![CDATA[6]]></Details>
<Time><![CDATA[9/17/2019 - 12:36:25]]></Time>
<TimeTick>1568703985</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="82" Source="Action1" SourceLine="9" >
<Disp><![CDATA[fromCity.GetItem]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[toCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["San Francisco"]]></Details>
<Time><![CDATA[9/17/2019 - 12:36:27]]></Time>
<TimeTick>1568703987</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="84" Source="Action1" SourceLine="10" >
<Disp><![CDATA[toCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[FIND FLIGHTS.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/17/2019 - 12:36:27]]></Time>
<TimeTick>1568703987</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="86" Source="Action1" SourceLine="11" >
<Disp><![CDATA[FIND FLIGHTS.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[BACK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/17/2019 - 12:36:28]]></Time>
<TimeTick>1568703988</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="88" Source="Action1" SourceLine="12" >
<Disp><![CDATA[BACK.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[fromCity.GetItem]]></Obj>
<Details plainTxt="False" ><![CDATA[6]]></Details>
<Time><![CDATA[9/17/2019 - 12:36:28]]></Time>
<TimeTick>1568703988</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="90" Source="Action1" SourceLine="7" >
<Disp><![CDATA[fromCity.GetItem]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[fromCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["San Francisco"]]></Details>
<Time><![CDATA[9/17/2019 - 12:36:29]]></Time>
<TimeTick>1568703989</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="92" Source="Action1" SourceLine="8" >
<Disp><![CDATA[fromCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[fromCity.GetItem]]></Obj>
<Details plainTxt="False" ><![CDATA[7]]></Details>
<Time><![CDATA[9/17/2019 - 12:36:29]]></Time>
<TimeTick>1568703989</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="94" Source="Action1" SourceLine="9" >
<Disp><![CDATA[fromCity.GetItem]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[toCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Seattle"]]></Details>
<Time><![CDATA[9/17/2019 - 12:36:30]]></Time>
<TimeTick>1568703990</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="96" Source="Action1" SourceLine="10" >
<Disp><![CDATA[toCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[FIND FLIGHTS.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/17/2019 - 12:36:30]]></Time>
<TimeTick>1568703990</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="98" Source="Action1" SourceLine="11" >
<Disp><![CDATA[FIND FLIGHTS.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[BACK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/17/2019 - 12:36:31]]></Time>
<TimeTick>1568703991</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="100" Source="Action1" SourceLine="12" >
<Disp><![CDATA[BACK.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[fromCity.GetItem]]></Obj>
<Details plainTxt="False" ><![CDATA[7]]></Details>
<Time><![CDATA[9/17/2019 - 12:36:31]]></Time>
<TimeTick>1568703991</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="102" Source="Action1" SourceLine="7" >
<Disp><![CDATA[fromCity.GetItem]]></Disp>
</NodeArgs>
</Step>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[fromCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Seattle"]]></Details>
<Time><![CDATA[9/17/2019 - 12:36:31]]></Time>
<TimeTick>1568703991</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="104" Source="Action1" SourceLine="8" >
<Disp><![CDATA[fromCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA[fromCity.GetItem]]></Obj>
<Details plainTxt="False" ><![CDATA[8]]></Details>
<Time><![CDATA[9/17/2019 - 12:36:32]]></Time>
<TimeTick>1568703992</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="106" Source="Action1" SourceLine="9" >
<Disp><![CDATA[fromCity.GetItem]]></Disp>
</NodeArgs>
</Step>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[toCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Sydney"]]></Details>
<Time><![CDATA[9/17/2019 - 12:36:32]]></Time>
<TimeTick>1568703992</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="108" Source="Action1" SourceLine="10" >
<Disp><![CDATA[toCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA[FIND FLIGHTS.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/17/2019 - 12:36:33]]></Time>
<TimeTick>1568703993</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="110" Source="Action1" SourceLine="11" >
<Disp><![CDATA[FIND FLIGHTS.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA[BACK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/17/2019 - 12:36:33]]></Time>
<TimeTick>1568703993</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="112" Source="Action1" SourceLine="12" >
<Disp><![CDATA[BACK.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T58">
<Obj plainTxt="False" ><![CDATA[fromCity.GetItem]]></Obj>
<Details plainTxt="False" ><![CDATA[8]]></Details>
<Time><![CDATA[9/17/2019 - 12:36:34]]></Time>
<TimeTick>1568703994</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="114" Source="Action1" SourceLine="7" >
<Disp><![CDATA[fromCity.GetItem]]></Disp>
</NodeArgs>
</Step>
<Step rID="T59">
<Obj plainTxt="False" ><![CDATA[fromCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Sydney"]]></Details>
<Time><![CDATA[9/17/2019 - 12:36:34]]></Time>
<TimeTick>1568703994</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="116" Source="Action1" SourceLine="8" >
<Disp><![CDATA[fromCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T60">
<Obj plainTxt="False" ><![CDATA[fromCity.GetItem]]></Obj>
<Details plainTxt="False" ><![CDATA[9]]></Details>
<Time><![CDATA[9/17/2019 - 12:36:35]]></Time>
<TimeTick>1568703995</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="118" Source="Action1" SourceLine="9" >
<Disp><![CDATA[fromCity.GetItem]]></Disp>
</NodeArgs>
</Step>
<Step rID="T61">
<Obj plainTxt="False" ><![CDATA[toCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Zurich"]]></Details>
<Time><![CDATA[9/17/2019 - 12:36:35]]></Time>
<TimeTick>1568703995</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="120" Source="Action1" SourceLine="10" >
<Disp><![CDATA[toCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T62">
<Obj plainTxt="False" ><![CDATA[FIND FLIGHTS.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/17/2019 - 12:36:36]]></Time>
<TimeTick>1568703996</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="122" Source="Action1" SourceLine="11" >
<Disp><![CDATA[FIND FLIGHTS.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T63">
<Obj plainTxt="False" ><![CDATA[BACK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/17/2019 - 12:36:36]]></Time>
<TimeTick>1568703996</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="124" Source="Action1" SourceLine="12" >
<Disp><![CDATA[BACK.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T64">
<Obj plainTxt="False" ><![CDATA[fromCity.GetItem]]></Obj>
<Details plainTxt="False" ><![CDATA[9]]></Details>
<Time><![CDATA[9/17/2019 - 12:36:36]]></Time>
<TimeTick>1568703996</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="126" Source="Action1" SourceLine="7" >
<Disp><![CDATA[fromCity.GetItem]]></Disp>
</NodeArgs>
</Step>
<Step rID="T65">
<Obj plainTxt="False" ><![CDATA[fromCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Zurich"]]></Details>
<Time><![CDATA[9/17/2019 - 12:36:37]]></Time>
<TimeTick>1568703997</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="128" Source="Action1" SourceLine="8" >
<Disp><![CDATA[fromCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T66">
<Obj plainTxt="False" ><![CDATA[fromCity]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;identify&nbsp;the&nbsp;specified&nbsp;item&nbsp;of&nbsp;the&nbsp;fromCity&nbsp;object.&nbsp;Confirm&nbsp;that&nbsp;the&nbsp;specified&nbsp;item&nbsp;is&nbsp;included&nbsp;in&nbsp;the&nbsp;object's&nbsp;item&nbsp;collection.]]></Details>
<Time><![CDATA[9/17/2019 - 12:36:37]]></Time>
<TimeTick>1568703997</TimeTick>
<Step rID="T67">
<Obj plainTxt="False" ><![CDATA[fromCity]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>devname = fromCity<br>]]></Details>
<Time><![CDATA[9/17/2019 - 12:36:37]]></Time>
<TimeTick>1568703997</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="130" status="Warning" nType="Description" Source="Action1" SourceLine="9" >
<Disp><![CDATA[fromCity]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="8" nRep="129" status="Failed" nType="Run Error" Source="Action1" SourceLine="9" >
<Disp><![CDATA[fromCity]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="9" status="Failed" Source="Action1" SourceLine="1" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<Step rID="T68">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[9/17/2019 - 12:36:37]]></Time>
<TimeTick>1568703997</TimeTick>
<Step rID="T69">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the specified item of the fromCity object. Confirm that the specified item is included in the object's item collection.<BR/>Line (10): &quot;ToCity = WpfWindow(&quot;HPE MyFlight Sample Applicatio&quot;).WpfComboBox(&quot;fromCity&quot;).GetItem(i+1)&quot;. ]]></Details>
<Time><![CDATA[9/17/2019 - 12:36:37]]></Time>
<TimeTick>1568703997</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="132" status="Failed" Source="Action1" SourceLine="9" >
<Disp><![CDATA[Run Error]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf6.xml]]></Path>
<ASHilite><![CDATA[4132228]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T70">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[9/17/2019 - 12:36:41]]></Time>
<TimeTick>1568704001</TimeTick>
<NodeArgs eType="General" icon="10" nRep="133" status="Information" >
<Disp><![CDATA[Stop Run]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="131" status="Failed" Source="Action1" SourceLine="9" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf5.xml]]></Path>
<ASHilite><![CDATA[4132228]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Summary sTime="9/17/2019 - 12:36:09" eTime="9/17/2019 - 12:36:41" passed="0" failed="2" warnings="1" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="7" status="Failed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" status="Failed" >
<Disp><![CDATA[Debugging Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="9/17/2019 - 12:36:07" eTime="9/17/2019 - 12:36:41" passed="0" failed="2" warnings="1" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Failed" >
<Disp><![CDATA[Test Debugging Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>