<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="HPE Unified Functional Testing" productVer="14.02" os="" host="P3A-HYCQXJ2"><DocLocation><![CDATA[C:\Users\pdc3a-training.pdc3a\Documents\Unified Functional Testing\E2E]]></DocLocation></General>
<Doc rID="T1"   productName= "HPE Unified Functional Testing"  >
<DName><![CDATA[E2E]]></DName>
<Res><![CDATA[Res6]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[E2E_Action]]></AName>
<Action rID="T5">
<AName><![CDATA[Registration_Action [Registration]]]></AName>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Welcome: Mercury Tours]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[9/13/2019 - 15:02:54]]></Time>
<TimeTick>1568367174</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Welcome: Mercury Tours]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[9/13/2019 - 15:02:54]]></Time>
<TimeTick>1568367174</TimeTick>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[REGISTER.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/13/2019 - 15:02:54]]></Time>
<TimeTick>1568367174</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="13" Source="Registration_Action [Registration]" SourceLine="1" >
<Disp><![CDATA[REGISTER.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="12" Source="Registration_Action [Registration]" SourceLine="1" >
<Disp><![CDATA[Welcome: Mercury Tours]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Register: Mercury Tours_2]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[9/13/2019 - 15:02:56]]></Time>
<TimeTick>1568367176</TimeTick>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[firstName.Drag]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/13/2019 - 15:02:56]]></Time>
<TimeTick>1568367176</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="16" Source="Registration_Action [Registration]" SourceLine="2" >
<Disp><![CDATA[firstName.Drag]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[firstName.Drop]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/13/2019 - 15:02:56]]></Time>
<TimeTick>1568367176</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="19" Source="Registration_Action [Registration]" SourceLine="3" >
<Disp><![CDATA[firstName.Drop]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[firstName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["s"]]></Details>
<Time><![CDATA[9/13/2019 - 15:02:56]]></Time>
<TimeTick>1568367176</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="22" Source="Registration_Action [Registration]" SourceLine="4" >
<Disp><![CDATA[firstName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[lastName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["w"]]></Details>
<Time><![CDATA[9/13/2019 - 15:02:56]]></Time>
<TimeTick>1568367176</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="25" Source="Registration_Action [Registration]" SourceLine="5" >
<Disp><![CDATA[lastName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[phone.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["789456123"]]></Details>
<Time><![CDATA[9/13/2019 - 15:02:56]]></Time>
<TimeTick>1568367176</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="28" Source="Registration_Action [Registration]" SourceLine="6" >
<Disp><![CDATA[phone.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[phone.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["7894561230"]]></Details>
<Time><![CDATA[9/13/2019 - 15:02:57]]></Time>
<TimeTick>1568367177</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="31" Source="Registration_Action [Registration]" SourceLine="7" >
<Disp><![CDATA[phone.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[userName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["s@gmail.com"]]></Details>
<Time><![CDATA[9/13/2019 - 15:02:57]]></Time>
<TimeTick>1568367177</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="34" Source="Registration_Action [Registration]" SourceLine="8" >
<Disp><![CDATA[userName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[address1.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["p"]]></Details>
<Time><![CDATA[9/13/2019 - 15:02:57]]></Time>
<TimeTick>1568367177</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="37" Source="Registration_Action [Registration]" SourceLine="9" >
<Disp><![CDATA[address1.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[address2.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["p"]]></Details>
<Time><![CDATA[9/13/2019 - 15:02:57]]></Time>
<TimeTick>1568367177</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="40" Source="Registration_Action [Registration]" SourceLine="10" >
<Disp><![CDATA[address2.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[city.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["p"]]></Details>
<Time><![CDATA[9/13/2019 - 15:02:57]]></Time>
<TimeTick>1568367177</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="43" Source="Registration_Action [Registration]" SourceLine="11" >
<Disp><![CDATA[city.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[state.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["p"]]></Details>
<Time><![CDATA[9/13/2019 - 15:02:57]]></Time>
<TimeTick>1568367177</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="46" Source="Registration_Action [Registration]" SourceLine="12" >
<Disp><![CDATA[state.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[postalCode.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["p"]]></Details>
<Time><![CDATA[9/13/2019 - 15:02:58]]></Time>
<TimeTick>1568367178</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="49" Source="Registration_Action [Registration]" SourceLine="13" >
<Disp><![CDATA[postalCode.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[country.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["PAKISTAN"]]></Details>
<Time><![CDATA[9/13/2019 - 15:02:58]]></Time>
<TimeTick>1568367178</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="52" Source="Registration_Action [Registration]" SourceLine="14" >
<Disp><![CDATA[country.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[email.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["p"]]></Details>
<Time><![CDATA[9/13/2019 - 15:02:58]]></Time>
<TimeTick>1568367178</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="55" Source="Registration_Action [Registration]" SourceLine="15" >
<Disp><![CDATA[email.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[password.SetSecure]]></Obj>
<Details plainTxt="False" ><![CDATA["5d7b5ecfcfc8956f"]]></Details>
<Time><![CDATA[9/13/2019 - 15:02:58]]></Time>
<TimeTick>1568367178</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="58" Source="Registration_Action [Registration]" SourceLine="16" >
<Disp><![CDATA[password.SetSecure]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[confirmPassword.SetSecure]]></Obj>
<Details plainTxt="False" ><![CDATA["5d7b5ed2130096f37003"]]></Details>
<Time><![CDATA[9/13/2019 - 15:02:58]]></Time>
<TimeTick>1568367178</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="61" Source="Registration_Action [Registration]" SourceLine="17" >
<Disp><![CDATA[confirmPassword.SetSecure]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[country.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["INDIA"]]></Details>
<Time><![CDATA[9/13/2019 - 15:02:58]]></Time>
<TimeTick>1568367178</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="64" Source="Registration_Action [Registration]" SourceLine="18" >
<Disp><![CDATA[country.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[email.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["useristhi"]]></Details>
<Time><![CDATA[9/13/2019 - 15:02:58]]></Time>
<TimeTick>1568367178</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="67" Source="Registration_Action [Registration]" SourceLine="19" >
<Disp><![CDATA[email.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[email.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["useristhis"]]></Details>
<Time><![CDATA[9/13/2019 - 15:02:59]]></Time>
<TimeTick>1568367179</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="70" Source="Registration_Action [Registration]" SourceLine="20" >
<Disp><![CDATA[email.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[password.SetSecure]]></Obj>
<Details plainTxt="False" ><![CDATA["5d7b5ef6771838a889c739543610429bf325dd0a70ed"]]></Details>
<Time><![CDATA[9/13/2019 - 15:02:59]]></Time>
<TimeTick>1568367179</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="73" Source="Registration_Action [Registration]" SourceLine="21" >
<Disp><![CDATA[password.SetSecure]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[confirmPassword.SetSecure]]></Obj>
<Details plainTxt="False" ><![CDATA["5d7b5efa51d5120aea1a6f8d3c3ff641b8feeb4f22fa"]]></Details>
<Time><![CDATA[9/13/2019 - 15:02:59]]></Time>
<TimeTick>1568367179</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="76" Source="Registration_Action [Registration]" SourceLine="22" >
<Disp><![CDATA[confirmPassword.SetSecure]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[register.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/13/2019 - 15:02:59]]></Time>
<TimeTick>1568367179</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="79" Source="Registration_Action [Registration]" SourceLine="23" >
<Disp><![CDATA[register.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[country]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;identify&nbsp;the&nbsp;object&nbsp;"country"&nbsp;(of&nbsp;class&nbsp;WebList).<br/>Verify&nbsp;that&nbsp;this&nbsp;object's&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[9/13/2019 - 15:03:25]]></Time>
<TimeTick>1568367205</TimeTick>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[country]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Mercury Class = WebList<br>Html Tag = SELECT<br>_xpath = //DIV[1]/TABLE[1]/TBODY[1]/TR[1]/TD[2]/TABLE[1]/TBODY[1]/TR[4]/TD[1]/TABLE[1]/TBODY[1]/TR[1]/TD[2]/TABLE[1]/TBODY[1]/TR[5]/TD[1]/FORM[1]/TABLE[1]/TBODY[1]/TR[12]/TD[2]/SELECT[1]<br>|Visible Items = 1<br>Visible = -1<br>Name = country<br>Items Count = 264<br>Html Id = <br>default value = UNITED STATES<br>DHTML Class = <br>acc_name = <br>]]></Details>
<Time><![CDATA[9/13/2019 - 15:03:25]]></Time>
<TimeTick>1568367205</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="124" status="Warning" nType="Description" Source="Registration_Action [Registration]" SourceLine="24" >
<Disp><![CDATA[country]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="10" nRep="123" status="Failed" nType="Run Error" Source="Registration_Action [Registration]" SourceLine="24" >
<Disp><![CDATA[country]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="15" status="Failed" Source="Registration_Action [Registration]" SourceLine="2" >
<Disp><![CDATA[Register: Mercury Tours_2]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="11" status="Failed" Source="Registration_Action [Registration]" SourceLine="1" >
<Disp><![CDATA[Welcome: Mercury Tours]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[Welcome: Mercury Tours]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[9/13/2019 - 15:03:25]]></Time>
<TimeTick>1568367205</TimeTick>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object &quot;country&quot; (of class WebList).<BR/>Verify that this object's properties match an object currently displayed in your application.<BR/>Line (25): &quot;Browser(&quot;Welcome: Mercury Tours&quot;).Page(&quot;Register: Mercury Tours_2&quot;).WebList(&quot;country&quot;).Submit&quot;. ]]></Details>
<Time><![CDATA[9/13/2019 - 15:03:25]]></Time>
<TimeTick>1568367205</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="126" status="Failed" Source="Registration_Action [Registration]" SourceLine="24" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="125" status="Failed" Source="Registration_Action [Registration]" SourceLine="24" >
<Disp><![CDATA[Welcome: Mercury Tours]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="9/13/2019 - 15:02:54" eTime="9/13/2019 - 15:03:42" passed="0" failed="2" warnings="1" ></Summary>
<NodeArgs eType="StartAction" icon="5" nRep="8" status="Failed" >
<Disp><![CDATA[Registration_Action [Registration] Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T36">
<AName><![CDATA[Login_Action [LoginTest]]]></AName>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[Welcome: Mercury Tours]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[9/13/2019 - 15:03:42]]></Time>
<TimeTick>1568367222</TimeTick>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[Register: Mercury Tours_3]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[9/13/2019 - 15:03:42]]></Time>
<TimeTick>1568367222</TimeTick>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[sign-in.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/13/2019 - 15:03:42]]></Time>
<TimeTick>1568367222</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="133" Source="Login_Action [LoginTest]" SourceLine="1" >
<Disp><![CDATA[sign-in.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="132" Source="Login_Action [LoginTest]" SourceLine="1" >
<Disp><![CDATA[Register: Mercury Tours_3]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[Welcome: Mercury Tours]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[9/13/2019 - 15:03:44]]></Time>
<TimeTick>1568367224</TimeTick>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[userName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["useristhis"]]></Details>
<Time><![CDATA[9/13/2019 - 15:03:44]]></Time>
<TimeTick>1568367224</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="137" Source="Login_Action [LoginTest]" SourceLine="2" >
<Disp><![CDATA[userName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[password.SetSecure]]></Obj>
<Details plainTxt="False" ><![CDATA["5d7b6059cc0d5d7b7d574d95e9c91916b19711ba4d04"]]></Details>
<Time><![CDATA[9/13/2019 - 15:03:44]]></Time>
<TimeTick>1568367224</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="140" Source="Login_Action [LoginTest]" SourceLine="3" >
<Disp><![CDATA[password.SetSecure]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA["Sign-In"- Description mismatch]]></Obj>
<Details plainTxt="False" ><![CDATA[The object was not found using the test object description. Check the object's properties.]]></Details>
<Time><![CDATA[9/13/2019 - 15:04:05]]></Time>
<TimeTick>1568367245</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="182" status="Warning" Source="Login_Action [LoginTest]" SourceLine="4" >
<Disp><![CDATA["Sign-In"- Description mismatch]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA["Sign-In"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not found.</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>micclass=Image<br>image type=Image Button<br>html tag=INPUT<br>alt=Sign-In<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (1 objects found)&nbsp;</FONT></u><br>
micclass=Image<br>html tag=INPUT<br>]]></Details>
<Time><![CDATA[9/13/2019 - 15:04:05]]></Time>
<TimeTick>1568367245</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="183" Source="Login_Action [LoginTest]" SourceLine="4" >
<Disp><![CDATA["Sign-In"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[Sign-In.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/13/2019 - 15:04:05]]></Time>
<TimeTick>1568367245</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="184" Source="Login_Action [LoginTest]" SourceLine="4" >
<Disp><![CDATA[Sign-In.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="136" status="Warning" Source="Login_Action [LoginTest]" SourceLine="2" >
<Disp><![CDATA[Welcome: Mercury Tours]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[Find a Flight: Mercury]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[9/13/2019 - 15:04:21]]></Time>
<TimeTick>1568367261</TimeTick>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[SIGN-OFF]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;find&nbsp;the&nbsp;"SIGN-OFF"&nbsp;object's&nbsp;parent&nbsp;"Welcome:&nbsp;Mercury&nbsp;Tours"&nbsp;(class&nbsp;Browser).<br/>Verify&nbsp;that&nbsp;parent&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[9/13/2019 - 15:04:21]]></Time>
<TimeTick>1568367261</TimeTick>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[Welcome: Mercury Tours]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Mercury Class = Browser<br>CreationTime = 0<br>|Title = Welcome: Mercury Tours<br>openurl = http://newtours.demoaut.com<br>opentitle = Welcome: Mercury Tours<br>Opened By Testing Tool = -1<br>number of tabs = 1<br>Name = Welcome: Mercury Tours<br>Has Toolbar = -1<br>Has Status Bar = 0<br>Has Menu Bar = -1<br>]]></Details>
<Time><![CDATA[9/13/2019 - 15:04:21]]></Time>
<TimeTick>1568367261</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="208" status="Warning" nType="Parent description" Source="Login_Action [LoginTest]" SourceLine="5" >
<Disp><![CDATA[Welcome: Mercury Tours]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="8" nRep="207" status="Failed" nType="Run Error" Source="Login_Action [LoginTest]" SourceLine="5" >
<Disp><![CDATA[SIGN-OFF]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[9/13/2019 - 15:04:21]]></Time>
<TimeTick>1568367261</TimeTick>
<NodeArgs eType="General" icon="14" nRep="209" status="Information" >
<Disp><![CDATA[Stop Run]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="206" status="Failed" Source="Login_Action [LoginTest]" SourceLine="5" >
<Disp><![CDATA[Find a Flight: Mercury]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="131" status="Failed" Source="Login_Action [LoginTest]" SourceLine="1" >
<Disp><![CDATA[Welcome: Mercury Tours]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="9/13/2019 - 15:03:42" eTime="9/13/2019 - 15:04:21" passed="0" failed="1" warnings="2" ></Summary>
<NodeArgs eType="StartAction" icon="5" nRep="128" status="Failed" >
<Disp><![CDATA[Login_Action [LoginTest] Summary]]></Disp>
</NodeArgs>
</Action>
<Summary sTime="9/13/2019 - 15:02:54" eTime="9/13/2019 - 15:04:21" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="7" status="Failed" >
<Disp><![CDATA[E2E_Action Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" status="Failed" >
<Disp><![CDATA[E2E Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="9/13/2019 - 15:02:50" eTime="9/13/2019 - 15:04:21" passed="0" failed="3" warnings="3" stopped="True" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Failed" >
<Disp><![CDATA[Test E2E Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>