<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="HPE Unified Functional Testing" productVer="14.02" os="" host="P3A-HYCQXJ2"><DocLocation><![CDATA[C:\Users\pdc3a-training.pdc3a\Documents\Unified Functional Testing\CaseStudy1]]></DocLocation></General>
<Doc rID="T1"   productName= "HPE Unified Functional Testing"  >
<DName><![CDATA[CaseStudy1]]></DName>
<Res><![CDATA[Res48]]></Res>
<RunType fmStep="True" /><DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<Action rID="T3">
<AName><![CDATA[Action1]]></AName>
<Step rID="T4">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[9/18/2019 - 16:11:17]]></Time>
<TimeTick>1568803277</TimeTick>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[fromCity.GetItemsCount]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/18/2019 - 16:11:17]]></Time>
<TimeTick>1568803277</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="9" Source="Action1" SourceLine="64" >
<Disp><![CDATA[fromCity.GetItemsCount]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[fromCity.GetItem]]></Obj>
<Details plainTxt="False" ><![CDATA[1]]></Details>
<Time><![CDATA[9/18/2019 - 16:11:21]]></Time>
<TimeTick>1568803281</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="11" Source="Action1" SourceLine="68" >
<Disp><![CDATA[fromCity.GetItem]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[fromCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Frankfurt"]]></Details>
<Time><![CDATA[9/18/2019 - 16:11:26]]></Time>
<TimeTick>1568803286</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="13" Source="Action1" SourceLine="69" >
<Disp><![CDATA[fromCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[toCity.GetItem]]></Obj>
<Details plainTxt="False" ><![CDATA[1]]></Details>
<Time><![CDATA[9/18/2019 - 16:11:30]]></Time>
<TimeTick>1568803290</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="15" Source="Action1" SourceLine="70" >
<Disp><![CDATA[toCity.GetItem]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[toCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Frankfurt"]]></Details>
<Time><![CDATA[9/18/2019 - 16:11:35]]></Time>
<TimeTick>1568803295</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="17" Source="Action1" SourceLine="71" >
<Disp><![CDATA[toCity.Select]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="8" Source="Action1" SourceLine="64" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj ><![CDATA[from_city_toCity]]></Obj>
<Details ><![CDATA[Frankfurt & Frankfurtare same]]></Details>
<Time><![CDATA[9/18/2019 - 16:11:35]]></Time>
<TimeTick>1568803295</TimeTick>
<NodeArgs eType="User" icon="6" nRep="18" status="Failed" Source="Action1" SourceLine="75" >
<Disp><![CDATA[from_city_toCity]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[9/18/2019 - 16:11:39]]></Time>
<TimeTick>1568803299</TimeTick>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[fromCity.GetItem]]></Obj>
<Details plainTxt="False" ><![CDATA[2]]></Details>
<Time><![CDATA[9/18/2019 - 16:11:40]]></Time>
<TimeTick>1568803300</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="21" Source="Action1" SourceLine="68" >
<Disp><![CDATA[fromCity.GetItem]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[fromCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["London"]]></Details>
<Time><![CDATA[9/18/2019 - 16:11:42]]></Time>
<TimeTick>1568803302</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="23" Source="Action1" SourceLine="69" >
<Disp><![CDATA[fromCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[toCity.GetItem]]></Obj>
<Details plainTxt="False" ><![CDATA[2]]></Details>
<Time><![CDATA[9/18/2019 - 16:11:47]]></Time>
<TimeTick>1568803307</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="25" Source="Action1" SourceLine="70" >
<Disp><![CDATA[toCity.GetItem]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[toCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["London"]]></Details>
<Time><![CDATA[9/18/2019 - 16:11:51]]></Time>
<TimeTick>1568803311</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="27" Source="Action1" SourceLine="71" >
<Disp><![CDATA[toCity.Select]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="20" Source="Action1" SourceLine="68" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj ><![CDATA[from_city_toCity]]></Obj>
<Details ><![CDATA[London & Londonare same]]></Details>
<Time><![CDATA[9/18/2019 - 16:11:51]]></Time>
<TimeTick>1568803311</TimeTick>
<NodeArgs eType="User" icon="6" nRep="28" status="Failed" Source="Action1" SourceLine="75" >
<Disp><![CDATA[from_city_toCity]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[9/18/2019 - 16:11:55]]></Time>
<TimeTick>1568803315</TimeTick>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[fromCity.GetItem]]></Obj>
<Details plainTxt="False" ><![CDATA[3]]></Details>
<Time><![CDATA[9/18/2019 - 16:11:55]]></Time>
<TimeTick>1568803315</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="31" Source="Action1" SourceLine="68" >
<Disp><![CDATA[fromCity.GetItem]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[fromCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Los Angeles"]]></Details>
<Time><![CDATA[9/18/2019 - 16:12:00]]></Time>
<TimeTick>1568803320</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="33" Source="Action1" SourceLine="69" >
<Disp><![CDATA[fromCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[toCity.GetItem]]></Obj>
<Details plainTxt="False" ><![CDATA[3]]></Details>
<Time><![CDATA[9/18/2019 - 16:12:04]]></Time>
<TimeTick>1568803324</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="35" Source="Action1" SourceLine="70" >
<Disp><![CDATA[toCity.GetItem]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[toCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Los Angeles"]]></Details>
<Time><![CDATA[9/18/2019 - 16:12:09]]></Time>
<TimeTick>1568803329</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="37" Source="Action1" SourceLine="71" >
<Disp><![CDATA[toCity.Select]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="30" Source="Action1" SourceLine="68" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj ><![CDATA[from_city_toCity]]></Obj>
<Details ><![CDATA[Los Angeles & Los Angelesare same]]></Details>
<Time><![CDATA[9/18/2019 - 16:12:09]]></Time>
<TimeTick>1568803329</TimeTick>
<NodeArgs eType="User" icon="6" nRep="38" status="Failed" Source="Action1" SourceLine="75" >
<Disp><![CDATA[from_city_toCity]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[9/18/2019 - 16:12:13]]></Time>
<TimeTick>1568803333</TimeTick>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[fromCity.GetItem]]></Obj>
<Details plainTxt="False" ><![CDATA[4]]></Details>
<Time><![CDATA[9/18/2019 - 16:12:13]]></Time>
<TimeTick>1568803333</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="41" Source="Action1" SourceLine="68" >
<Disp><![CDATA[fromCity.GetItem]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[fromCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Paris"]]></Details>
<Time><![CDATA[9/18/2019 - 16:12:16]]></Time>
<TimeTick>1568803336</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="43" Source="Action1" SourceLine="69" >
<Disp><![CDATA[fromCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[toCity.GetItem]]></Obj>
<Details plainTxt="False" ><![CDATA[4]]></Details>
<Time><![CDATA[9/18/2019 - 16:12:20]]></Time>
<TimeTick>1568803340</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="45" Source="Action1" SourceLine="70" >
<Disp><![CDATA[toCity.GetItem]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[toCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Paris"]]></Details>
<Time><![CDATA[9/18/2019 - 16:12:23]]></Time>
<TimeTick>1568803343</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="47" Source="Action1" SourceLine="71" >
<Disp><![CDATA[toCity.Select]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="40" Source="Action1" SourceLine="68" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj ><![CDATA[from_city_toCity]]></Obj>
<Details ><![CDATA[Paris & Parisare same]]></Details>
<Time><![CDATA[9/18/2019 - 16:12:23]]></Time>
<TimeTick>1568803343</TimeTick>
<NodeArgs eType="User" icon="6" nRep="48" status="Failed" Source="Action1" SourceLine="75" >
<Disp><![CDATA[from_city_toCity]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[9/18/2019 - 16:12:27]]></Time>
<TimeTick>1568803347</TimeTick>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[fromCity.GetItem]]></Obj>
<Details plainTxt="False" ><![CDATA[5]]></Details>
<Time><![CDATA[9/18/2019 - 16:12:27]]></Time>
<TimeTick>1568803347</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="51" Source="Action1" SourceLine="68" >
<Disp><![CDATA[fromCity.GetItem]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[fromCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Portland"]]></Details>
<Time><![CDATA[9/18/2019 - 16:12:30]]></Time>
<TimeTick>1568803350</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="53" Source="Action1" SourceLine="69" >
<Disp><![CDATA[fromCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[toCity.GetItem]]></Obj>
<Details plainTxt="False" ><![CDATA[5]]></Details>
<Time><![CDATA[9/18/2019 - 16:12:34]]></Time>
<TimeTick>1568803354</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="55" Source="Action1" SourceLine="70" >
<Disp><![CDATA[toCity.GetItem]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[toCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Portland"]]></Details>
<Time><![CDATA[9/18/2019 - 16:12:37]]></Time>
<TimeTick>1568803357</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="57" Source="Action1" SourceLine="71" >
<Disp><![CDATA[toCity.Select]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="50" Source="Action1" SourceLine="68" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj ><![CDATA[from_city_toCity]]></Obj>
<Details ><![CDATA[Portland & Portlandare same]]></Details>
<Time><![CDATA[9/18/2019 - 16:12:37]]></Time>
<TimeTick>1568803357</TimeTick>
<NodeArgs eType="User" icon="6" nRep="58" status="Failed" Source="Action1" SourceLine="75" >
<Disp><![CDATA[from_city_toCity]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[9/18/2019 - 16:12:42]]></Time>
<TimeTick>1568803362</TimeTick>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[fromCity.GetItem]]></Obj>
<Details plainTxt="False" ><![CDATA[6]]></Details>
<Time><![CDATA[9/18/2019 - 16:12:42]]></Time>
<TimeTick>1568803362</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="61" Source="Action1" SourceLine="68" >
<Disp><![CDATA[fromCity.GetItem]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[fromCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["San Francisco"]]></Details>
<Time><![CDATA[9/18/2019 - 16:12:44]]></Time>
<TimeTick>1568803364</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="63" Source="Action1" SourceLine="69" >
<Disp><![CDATA[fromCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[toCity.GetItem]]></Obj>
<Details plainTxt="False" ><![CDATA[6]]></Details>
<Time><![CDATA[9/18/2019 - 16:12:49]]></Time>
<TimeTick>1568803369</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="65" Source="Action1" SourceLine="70" >
<Disp><![CDATA[toCity.GetItem]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[toCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["San Francisco"]]></Details>
<Time><![CDATA[9/18/2019 - 16:12:53]]></Time>
<TimeTick>1568803373</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="67" Source="Action1" SourceLine="71" >
<Disp><![CDATA[toCity.Select]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="60" Source="Action1" SourceLine="68" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj ><![CDATA[from_city_toCity]]></Obj>
<Details ><![CDATA[San Francisco & San Franciscoare same]]></Details>
<Time><![CDATA[9/18/2019 - 16:12:53]]></Time>
<TimeTick>1568803373</TimeTick>
<NodeArgs eType="User" icon="6" nRep="68" status="Failed" Source="Action1" SourceLine="75" >
<Disp><![CDATA[from_city_toCity]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[9/18/2019 - 16:12:58]]></Time>
<TimeTick>1568803378</TimeTick>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[fromCity.GetItem]]></Obj>
<Details plainTxt="False" ><![CDATA[7]]></Details>
<Time><![CDATA[9/18/2019 - 16:12:58]]></Time>
<TimeTick>1568803378</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="71" Source="Action1" SourceLine="68" >
<Disp><![CDATA[fromCity.GetItem]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[fromCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Seattle"]]></Details>
<Time><![CDATA[9/18/2019 - 16:13:00]]></Time>
<TimeTick>1568803380</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="73" Source="Action1" SourceLine="69" >
<Disp><![CDATA[fromCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[toCity.GetItem]]></Obj>
<Details plainTxt="False" ><![CDATA[7]]></Details>
<Time><![CDATA[9/18/2019 - 16:13:05]]></Time>
<TimeTick>1568803385</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="75" Source="Action1" SourceLine="70" >
<Disp><![CDATA[toCity.GetItem]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[toCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Seattle"]]></Details>
<Time><![CDATA[9/18/2019 - 16:13:07]]></Time>
<TimeTick>1568803387</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="77" Source="Action1" SourceLine="71" >
<Disp><![CDATA[toCity.Select]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="70" Source="Action1" SourceLine="68" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj ><![CDATA[from_city_toCity]]></Obj>
<Details ><![CDATA[Seattle & Seattleare same]]></Details>
<Time><![CDATA[9/18/2019 - 16:13:07]]></Time>
<TimeTick>1568803387</TimeTick>
<NodeArgs eType="User" icon="6" nRep="78" status="Failed" Source="Action1" SourceLine="75" >
<Disp><![CDATA[from_city_toCity]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[9/18/2019 - 16:13:12]]></Time>
<TimeTick>1568803392</TimeTick>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[fromCity.GetItem]]></Obj>
<Details plainTxt="False" ><![CDATA[8]]></Details>
<Time><![CDATA[9/18/2019 - 16:13:12]]></Time>
<TimeTick>1568803392</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="81" Source="Action1" SourceLine="68" >
<Disp><![CDATA[fromCity.GetItem]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[fromCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Sydney"]]></Details>
<Time><![CDATA[9/18/2019 - 16:13:14]]></Time>
<TimeTick>1568803394</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="83" Source="Action1" SourceLine="69" >
<Disp><![CDATA[fromCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[toCity.GetItem]]></Obj>
<Details plainTxt="False" ><![CDATA[8]]></Details>
<Time><![CDATA[9/18/2019 - 16:13:19]]></Time>
<TimeTick>1568803399</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="85" Source="Action1" SourceLine="70" >
<Disp><![CDATA[toCity.GetItem]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[toCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Sydney"]]></Details>
<Time><![CDATA[9/18/2019 - 16:13:21]]></Time>
<TimeTick>1568803401</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="87" Source="Action1" SourceLine="71" >
<Disp><![CDATA[toCity.Select]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="80" Source="Action1" SourceLine="68" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<Step rID="T52">
<Obj ><![CDATA[from_city_toCity]]></Obj>
<Details ><![CDATA[Sydney & Sydneyare same]]></Details>
<Time><![CDATA[9/18/2019 - 16:13:22]]></Time>
<TimeTick>1568803402</TimeTick>
<NodeArgs eType="User" icon="6" nRep="88" status="Failed" Source="Action1" SourceLine="75" >
<Disp><![CDATA[from_city_toCity]]></Disp>
</NodeArgs>
</Step>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[9/18/2019 - 16:13:26]]></Time>
<TimeTick>1568803406</TimeTick>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA[fromCity.GetItem]]></Obj>
<Details plainTxt="False" ><![CDATA[9]]></Details>
<Time><![CDATA[9/18/2019 - 16:13:26]]></Time>
<TimeTick>1568803406</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="91" Source="Action1" SourceLine="68" >
<Disp><![CDATA[fromCity.GetItem]]></Disp>
</NodeArgs>
</Step>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[fromCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Zurich"]]></Details>
<Time><![CDATA[9/18/2019 - 16:13:29]]></Time>
<TimeTick>1568803409</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="93" Source="Action1" SourceLine="69" >
<Disp><![CDATA[fromCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA[toCity.GetItem]]></Obj>
<Details plainTxt="False" ><![CDATA[9]]></Details>
<Time><![CDATA[9/18/2019 - 16:13:33]]></Time>
<TimeTick>1568803413</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="95" Source="Action1" SourceLine="70" >
<Disp><![CDATA[toCity.GetItem]]></Disp>
</NodeArgs>
</Step>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA[toCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Zurich"]]></Details>
<Time><![CDATA[9/18/2019 - 16:13:36]]></Time>
<TimeTick>1568803416</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="97" Source="Action1" SourceLine="71" >
<Disp><![CDATA[toCity.Select]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="90" Source="Action1" SourceLine="68" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<Step rID="T58">
<Obj ><![CDATA[from_city_toCity]]></Obj>
<Details ><![CDATA[Zurich & Zurichare same]]></Details>
<Time><![CDATA[9/18/2019 - 16:13:36]]></Time>
<TimeTick>1568803416</TimeTick>
<NodeArgs eType="User" icon="6" nRep="98" status="Failed" Source="Action1" SourceLine="75" >
<Disp><![CDATA[from_city_toCity]]></Disp>
</NodeArgs>
</Step>
<Step rID="T59">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[9/18/2019 - 16:13:40]]></Time>
<TimeTick>1568803420</TimeTick>
<Step rID="T60">
<Obj plainTxt="False" ><![CDATA[fromCity]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;identify&nbsp;the&nbsp;specified&nbsp;item&nbsp;of&nbsp;the&nbsp;fromCity&nbsp;object.&nbsp;Confirm&nbsp;that&nbsp;the&nbsp;specified&nbsp;item&nbsp;is&nbsp;included&nbsp;in&nbsp;the&nbsp;object's&nbsp;item&nbsp;collection.]]></Details>
<Time><![CDATA[9/18/2019 - 16:13:40]]></Time>
<TimeTick>1568803420</TimeTick>
<Step rID="T61">
<Obj plainTxt="False" ><![CDATA[fromCity]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>devname = fromCity<br>]]></Details>
<Time><![CDATA[9/18/2019 - 16:13:40]]></Time>
<TimeTick>1568803420</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="101" status="Warning" nType="Description" Source="Action1" SourceLine="68" >
<Disp><![CDATA[fromCity]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="100" status="Failed" nType="Run Error" Source="Action1" SourceLine="68" >
<Disp><![CDATA[fromCity]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="99" status="Failed" Source="Action1" SourceLine="68" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<Step rID="T62">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[9/18/2019 - 16:13:40]]></Time>
<TimeTick>1568803420</TimeTick>
<Step rID="T63">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the specified item of the fromCity object. Confirm that the specified item is included in the object's item collection.<BR/>Line (69): &quot;from_city= WpfWindow(&quot;HPE MyFlight Sample Applicatio&quot;).WpfComboBox(&quot;fromCity&quot;).GetItem(i)&quot;. ]]></Details>
<Time><![CDATA[9/18/2019 - 16:13:41]]></Time>
<TimeTick>1568803421</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="103" status="Failed" Source="Action1" SourceLine="68" >
<Disp><![CDATA[Run Error]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf4.xml]]></Path>
<ASHilite><![CDATA[985614]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T64">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[9/18/2019 - 16:13:51]]></Time>
<TimeTick>1568803431</TimeTick>
<NodeArgs eType="General" icon="8" nRep="104" status="Information" >
<Disp><![CDATA[Stop Run]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="102" status="Failed" Source="Action1" SourceLine="68" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf3.xml]]></Path>
<ASHilite><![CDATA[985614]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Summary sTime="9/18/2019 - 16:11:12" eTime="9/18/2019 - 16:13:51" passed="0" failed="11" warnings="1" ></Summary>
<NodeArgs eType="StartAction" icon="3" nRep="6" status="Failed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<Summary sTime="9/18/2019 - 16:11:10" eTime="9/18/2019 - 16:13:51" passed="0" failed="11" warnings="1" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Failed" >
<Disp><![CDATA[Test CaseStudy1 Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>