<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="HPE Unified Functional Testing" productVer="14.02" os="" host="P3A-HYCQXJ2"><DocLocation><![CDATA[C:\Users\pdc3a-training.pdc3a\Documents\Unified Functional Testing\E2E]]></DocLocation></General>
<Doc rID="T1"   productName= "HPE Unified Functional Testing"  >
<DName><![CDATA[E2E]]></DName>
<Res><![CDATA[Res12]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[E2E_Action]]></AName>
<Action rID="T5">
<AName><![CDATA[Registration_Action [Registration]]]></AName>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Welcome: Mercury Tours]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[9/13/2019 - 16:48:12]]></Time>
<TimeTick>1568373492</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Welcome: Mercury Tours]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[9/13/2019 - 16:48:12]]></Time>
<TimeTick>1568373492</TimeTick>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[REGISTER.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/13/2019 - 16:48:12]]></Time>
<TimeTick>1568373492</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="13" Source="Registration_Action [Registration]" SourceLine="1" >
<Disp><![CDATA[REGISTER.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="12" Source="Registration_Action [Registration]" SourceLine="1" >
<Disp><![CDATA[Welcome: Mercury Tours]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Register: Mercury Tours_2]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[9/13/2019 - 16:48:14]]></Time>
<TimeTick>1568373494</TimeTick>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[firstName.Drag]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/13/2019 - 16:48:14]]></Time>
<TimeTick>1568373494</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="16" Source="Registration_Action [Registration]" SourceLine="2" >
<Disp><![CDATA[firstName.Drag]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[firstName.Drop]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/13/2019 - 16:48:14]]></Time>
<TimeTick>1568373494</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="19" Source="Registration_Action [Registration]" SourceLine="3" >
<Disp><![CDATA[firstName.Drop]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[firstName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["s"]]></Details>
<Time><![CDATA[9/13/2019 - 16:48:14]]></Time>
<TimeTick>1568373494</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="22" Source="Registration_Action [Registration]" SourceLine="4" >
<Disp><![CDATA[firstName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[lastName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["w"]]></Details>
<Time><![CDATA[9/13/2019 - 16:48:14]]></Time>
<TimeTick>1568373494</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="25" Source="Registration_Action [Registration]" SourceLine="5" >
<Disp><![CDATA[lastName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[phone.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["789456123"]]></Details>
<Time><![CDATA[9/13/2019 - 16:48:14]]></Time>
<TimeTick>1568373494</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="28" Source="Registration_Action [Registration]" SourceLine="6" >
<Disp><![CDATA[phone.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[phone.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["7894561230"]]></Details>
<Time><![CDATA[9/13/2019 - 16:48:15]]></Time>
<TimeTick>1568373495</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="31" Source="Registration_Action [Registration]" SourceLine="7" >
<Disp><![CDATA[phone.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[userName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["s@gmail.com"]]></Details>
<Time><![CDATA[9/13/2019 - 16:48:15]]></Time>
<TimeTick>1568373495</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="34" Source="Registration_Action [Registration]" SourceLine="8" >
<Disp><![CDATA[userName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[address1.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["p"]]></Details>
<Time><![CDATA[9/13/2019 - 16:48:15]]></Time>
<TimeTick>1568373495</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="37" Source="Registration_Action [Registration]" SourceLine="9" >
<Disp><![CDATA[address1.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[address2.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["p"]]></Details>
<Time><![CDATA[9/13/2019 - 16:48:15]]></Time>
<TimeTick>1568373495</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="40" Source="Registration_Action [Registration]" SourceLine="10" >
<Disp><![CDATA[address2.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[city.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["p"]]></Details>
<Time><![CDATA[9/13/2019 - 16:48:15]]></Time>
<TimeTick>1568373495</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="43" Source="Registration_Action [Registration]" SourceLine="11" >
<Disp><![CDATA[city.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[state.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["p"]]></Details>
<Time><![CDATA[9/13/2019 - 16:48:15]]></Time>
<TimeTick>1568373495</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="46" Source="Registration_Action [Registration]" SourceLine="12" >
<Disp><![CDATA[state.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[postalCode.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["p"]]></Details>
<Time><![CDATA[9/13/2019 - 16:48:16]]></Time>
<TimeTick>1568373496</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="49" Source="Registration_Action [Registration]" SourceLine="13" >
<Disp><![CDATA[postalCode.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[country.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["PAKISTAN"]]></Details>
<Time><![CDATA[9/13/2019 - 16:48:16]]></Time>
<TimeTick>1568373496</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="52" Source="Registration_Action [Registration]" SourceLine="14" >
<Disp><![CDATA[country.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[email.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["p"]]></Details>
<Time><![CDATA[9/13/2019 - 16:48:16]]></Time>
<TimeTick>1568373496</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="55" Source="Registration_Action [Registration]" SourceLine="15" >
<Disp><![CDATA[email.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[password.SetSecure]]></Obj>
<Details plainTxt="False" ><![CDATA["5d7b5ecfcfc8956f"]]></Details>
<Time><![CDATA[9/13/2019 - 16:48:16]]></Time>
<TimeTick>1568373496</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="58" Source="Registration_Action [Registration]" SourceLine="16" >
<Disp><![CDATA[password.SetSecure]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[confirmPassword.SetSecure]]></Obj>
<Details plainTxt="False" ><![CDATA["5d7b5ed2130096f37003"]]></Details>
<Time><![CDATA[9/13/2019 - 16:48:16]]></Time>
<TimeTick>1568373496</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="61" Source="Registration_Action [Registration]" SourceLine="17" >
<Disp><![CDATA[confirmPassword.SetSecure]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[country.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["INDIA"]]></Details>
<Time><![CDATA[9/13/2019 - 16:48:16]]></Time>
<TimeTick>1568373496</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="64" Source="Registration_Action [Registration]" SourceLine="18" >
<Disp><![CDATA[country.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[email.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["useristhi"]]></Details>
<Time><![CDATA[9/13/2019 - 16:48:16]]></Time>
<TimeTick>1568373496</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="67" Source="Registration_Action [Registration]" SourceLine="19" >
<Disp><![CDATA[email.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[email.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["useristhis"]]></Details>
<Time><![CDATA[9/13/2019 - 16:48:16]]></Time>
<TimeTick>1568373496</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="70" Source="Registration_Action [Registration]" SourceLine="20" >
<Disp><![CDATA[email.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[password.SetSecure]]></Obj>
<Details plainTxt="False" ><![CDATA["5d7b5ef6771838a889c739543610429bf325dd0a70ed"]]></Details>
<Time><![CDATA[9/13/2019 - 16:48:17]]></Time>
<TimeTick>1568373497</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="73" Source="Registration_Action [Registration]" SourceLine="21" >
<Disp><![CDATA[password.SetSecure]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[confirmPassword.SetSecure]]></Obj>
<Details plainTxt="False" ><![CDATA["5d7b5efa51d5120aea1a6f8d3c3ff641b8feeb4f22fa"]]></Details>
<Time><![CDATA[9/13/2019 - 16:48:17]]></Time>
<TimeTick>1568373497</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="76" Source="Registration_Action [Registration]" SourceLine="22" >
<Disp><![CDATA[confirmPassword.SetSecure]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[register.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/13/2019 - 16:48:17]]></Time>
<TimeTick>1568373497</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="79" Source="Registration_Action [Registration]" SourceLine="23" >
<Disp><![CDATA[register.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="15" Source="Registration_Action [Registration]" SourceLine="2" >
<Disp><![CDATA[Register: Mercury Tours_2]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="11" Source="Registration_Action [Registration]" SourceLine="1" >
<Disp><![CDATA[Welcome: Mercury Tours]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="9/13/2019 - 16:48:12" eTime="9/13/2019 - 16:48:23" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="5" nRep="8" >
<Disp><![CDATA[Registration_Action [Registration] Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T32">
<AName><![CDATA[Login_Action [LoginTest]]]></AName>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[Welcome: Mercury Tours]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[9/13/2019 - 16:48:44]]></Time>
<TimeTick>1568373524</TimeTick>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[Register: Mercury Tours_3]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[9/13/2019 - 16:48:44]]></Time>
<TimeTick>1568373524</TimeTick>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA["sign-in"- Description mismatch]]></Obj>
<Details plainTxt="False" ><![CDATA[The object was not found using the test object description. Check the object's properties.]]></Details>
<Time><![CDATA[9/13/2019 - 16:48:44]]></Time>
<TimeTick>1568373524</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="86" status="Warning" Source="Login_Action [LoginTest]" SourceLine="2" >
<Disp><![CDATA["sign-in"- Description mismatch]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA["sign-in"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not found.</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>text=sign-in<br>micclass=Link<br>html tag=A<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (11 objects found)&nbsp;</FONT></u><br>
micclass=Link<br>html tag=A<br><br><FONT face=Verdana size=2><u>Optional filter properties</FONT></u><br>
text=sign-in<SPAN class=Failed> (Skipped)</SPAN><br>html id=<SPAN class=passed> (Used</SPAN>, 11 matches)</SPAN><br>class=<SPAN class=passed> (Used</SPAN>, 11 matches)</SPAN><br>name=sign-in<SPAN class=Failed> (Skipped)</SPAN><br>href=http://newtours.demoaut.com/mercurysignon.php<SPAN class=passed> (Used</SPAN>, 1 matches)</SPAN><br>visible=1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>acc_name=<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>]]></Details>
<Time><![CDATA[9/13/2019 - 16:48:44]]></Time>
<TimeTick>1568373524</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="87" Source="Login_Action [LoginTest]" SourceLine="2" >
<Disp><![CDATA["sign-in"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[sign-in.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/13/2019 - 16:48:44]]></Time>
<TimeTick>1568373524</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="88" Source="Login_Action [LoginTest]" SourceLine="2" >
<Disp><![CDATA[sign-in.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="85" status="Warning" Source="Login_Action [LoginTest]" SourceLine="2" >
<Disp><![CDATA[Register: Mercury Tours_3]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[Sign-on: Mercury Tours]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[9/13/2019 - 16:48:50]]></Time>
<TimeTick>1568373530</TimeTick>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[userName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["useristhis"]]></Details>
<Time><![CDATA[9/13/2019 - 16:48:50]]></Time>
<TimeTick>1568373530</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="92" Source="Login_Action [LoginTest]" SourceLine="3" >
<Disp><![CDATA[userName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[password.SetSecure]]></Obj>
<Details plainTxt="False" ><![CDATA["5d7b6c1249134075b5239fa6fea4240bbad023e217c6"]]></Details>
<Time><![CDATA[9/13/2019 - 16:48:50]]></Time>
<TimeTick>1568373530</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="95" Source="Login_Action [LoginTest]" SourceLine="4" >
<Disp><![CDATA[password.SetSecure]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[Login.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/13/2019 - 16:48:50]]></Time>
<TimeTick>1568373530</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="98" Source="Login_Action [LoginTest]" SourceLine="5" >
<Disp><![CDATA[Login.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="91" Source="Login_Action [LoginTest]" SourceLine="3" >
<Disp><![CDATA[Sign-on: Mercury Tours]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="84" status="Warning" Source="Login_Action [LoginTest]" SourceLine="2" >
<Disp><![CDATA[Welcome: Mercury Tours]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="9/13/2019 - 16:48:23" eTime="9/13/2019 - 16:48:50" passed="0" failed="0" warnings="1" ></Summary>
<NodeArgs eType="StartAction" icon="5" nRep="81" status="Warning" >
<Disp><![CDATA[Login_Action [LoginTest] Summary]]></Disp>
</NodeArgs>
</Action>
<Summary sTime="9/13/2019 - 16:48:12" eTime="9/13/2019 - 16:48:51" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="7" status="Warning" >
<Disp><![CDATA[E2E_Action Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" status="Warning" >
<Disp><![CDATA[E2E Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="9/13/2019 - 16:48:08" eTime="9/13/2019 - 16:48:51" passed="0" failed="0" warnings="1" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Warning" >
<Disp><![CDATA[Test E2E Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>